# Generated by Django 4.1 on 2022-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirusSeqInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus_cd', models.CharField(max_length=3)),
                ('uniprot_rec', models.TextField()),
                ('linge_nm', models.TextField()),
                ('linge_dc', models.TextField()),
                ('seq_rgin_st_lc', models.IntegerField()),
                ('seq_rgin_end_lc', models.IntegerField()),
                ('genomic_st_lc', models.IntegerField(null=True)),
                ('genomic_end_lc', models.IntegerField(null=True)),
                ('aa_seq', models.TextField()),
                ('regist_id', models.TextField()),
                ('regist_dt', models.DateTimeField()),
                ('del_yn', models.CharField(default='N', max_length=1)),
                ('del_dt', models.DateTimeField(null=True)),
            ],
        ),
    ]
