# Generated by Django 4.1 on 2022-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_virusseqinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='virusseqinfo',
            name='rna_seq',
            field=models.TextField(null=True),
        ),
    ]
