# Generated by Django 4.1 on 2022-11-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_virusseqinfo_rna_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='virusseqinfo',
            name='mut_nm',
            field=models.TextField(default=''),
        ),
    ]
