# Generated by Django 4.1 on 2022-11-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_virusseqinfo_mut_nm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virusseqinfo',
            old_name='mut_nm',
            new_name='virus_mut_nm',
        ),
    ]
