# Generated by Django 4.1 on 2022-11-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_rename_mut_nm_virusseqinfo_virus_mut_nm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virusseqinfo',
            old_name='linge_dc',
            new_name='domain_dc',
        ),
        migrations.RenameField(
            model_name='virusseqinfo',
            old_name='linge_nm',
            new_name='domain_nm',
        ),
    ]
