# Generated by Django 4.1 on 2022-11-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_aive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdctninfo',
            name='prdctn_sj',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prdctninfo',
            name='public_yn',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='prdctninfo',
            name='trget_seq_rgi_end_lc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prdctninfo',
            name='trget_seq_rgi_st_lc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prdctninfo',
            name='trget_virus',
            field=models.TextField(default='All'),
        ),
    ]
