# Generated by Django 4.1 on 2022-11-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_aive', '0003_rename_trget_seq_rgi_end_lc_prdctninfo_trget_seq_rgin_end_lc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdctninfo',
            name='virus_mut_nm',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='prdctninfo',
            name='trget_virus',
            field=models.TextField(default='ALL'),
        ),
    ]
