# Generated by Django 4.1 on 2022-12-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_aive', '0004_prdctninfo_virus_mut_nm_alter_prdctninfo_trget_virus'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdctninfo',
            name='domain_nm',
            field=models.TextField(default=''),
        ),
    ]
