# Generated by Django 4.1 on 2022-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_aive', '0005_prdctninfo_domain_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdctninfo',
            name='output_virus_rna_seq_1',
            field=models.TextField(null=True),
        ),
    ]
